/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Workshop Overview',
    },
    {
      type: 'category',
      label: 'Project Setup',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'project-setup/getting-started',
          label: "Getting Started"
        },
        {
          type: 'doc',
          id: 'project-setup/backend-orientation',
          label: "Backend Orientation"
        },
        {
          type: 'doc',
          id: 'project-setup/run-local-server-database',
          label: "Run Local Server and Database"
        },
      ],
    },
  ],
};

module.exports = sidebars;
